In [1]:
import numpy as np
import math

In [2]:
def compute_distances_one_loop(X_train, X):
        num_test = X.shape[0]
        num_train = X_train.shape[0]
        dists = np.zeros((num_test, num_train))
        for i in xrange(num_test):
            diff_matrix =  X_train - X[i]
            sqrd_mag = np.linalg.norm(diff_matrix, axis=1)
            dists[i, :] = np.sqrt(sqrd_mag)
        return dists

In [6]:
X_train = np.arange(0, 16, 2).reshape(4,2)
X_train = np.arange(1, 9, 1).reshape(4,2)
X = np.arange(0, 6, 1).reshape(3,2)
print X_train
print 
print X

[[1 2]
 [3 4]
 [5 6]
 [7 8]]

[[0 1]
 [2 3]
 [4 5]]


In [11]:
    num_test = X.shape[0]
    num_train = X_train.shape[0]
    dists = np.zeros((num_test, num_train)) 

    tr2 = (X_train ** 2).sum(axis = 1).reshape(1, X_train.shape[0])
    tst2 = (X ** 2).T.sum(axis = 0).reshape(X.shape[0],1)

    AxB = 2 * np.matmul(X, X_train.T)
    print AxB
    a2pb2 = tst2 + tr2
    print a2pb2
    dists = np.sqrt(np.sqrt(np.abs(a2pb2 - AxB)))
    print dists

[[  4   8  12  16]
 [ 16  36  56  76]
 [ 28  64 100 136]]
[[  6  26  62 114]
 [ 18  38  74 126]
 [ 46  66 102 154]]
[[ 1.18920712  2.05976714  2.65914795  3.14634628]
 [ 1.18920712  1.18920712  2.05976714  2.65914795]
 [ 2.05976714  1.18920712  1.18920712  2.05976714]]


In [12]:
# Now implement the fully vectorized version inside compute_distances_no_loops
# and run the code
dists_one = compute_distances_one_loop(X_train, X)
print dists_one**2
print dists**2

# check that the distance matrix agrees with the one we computed before:
difference = np.linalg.norm(dists - dists_one, ord='fro')
print 'Difference was: %f' % (difference, )
if difference < 0.001:
  print 'Good! The distance matrices are the same'
else:
  print 'Uh-oh! The distance matrices are different'

[[ 1.41421356  4.24264069  7.07106781  9.89949494]
 [ 1.41421356  1.41421356  4.24264069  7.07106781]
 [ 4.24264069  1.41421356  1.41421356  4.24264069]]
[[ 1.41421356  4.24264069  7.07106781  9.89949494]
 [ 1.41421356  1.41421356  4.24264069  7.07106781]
 [ 4.24264069  1.41421356  1.41421356  4.24264069]]
Difference was: 0.000000
Good! The distance matrices are the same


num_test = X.shape[0]
num_train = X_train.shape[0]
dists = np.zeros((num_test, num_train)) 

tr2 = (X_train ** 2).sum(axis = 1).reshape(1, X_train.shape[0])
tst2 = (X ** 2).T.sum(axis = 0).reshape(X.shape[0],1)

#print tr2 #print tst2 #print X_train, "\n\n", X
AxB = 2 * np.matmul(X_train, X)

#print "\n2 * AxB:\n", AxB #print
a2xb2 = tst2 + tr2

dists = np.sqrt(np.abs(a2xb2 - AxB.T))

print dists
#print tr2, tr2.shape,  "\n" #print tst2, "\n", tst2.shape